# Generated by Django 3.0.2 on 2020-03-03 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 5, 45, 15, 125945), verbose_name='date published'),
        ),
    ]
